# See https://developers.google.com/appengine/docs/php/config/appconfig.

application: drupal
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
# Default handler for requests (wrapper which will forward to index.php).
- url: /
  script: wrapper.php

# Handle static requests.
- url: /(.*\.(ico$|jpg$|png$|gif$|htm$|html$|css$|js$))
  # Location from which to serve static files.
  static_files: \1
  # Upload static files for static serving.
  upload: (.*\.(ico$|jpg$|png$|gif$|htm$|html$|css$|js$))
  # Ensures that a copy of the static files is left for Drupal during runtime.
  application_readable: true

# Catch all unhandled requests and pass to wrapper.php which will simulate
# mod_rewrite by forwarding the requests to index.php?q=...
- url: /(.+)
  script: wrapper.php
